
"use client";

import { useDevopsSim } from "@/providers/devops-sim-provider";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  CardFooter
} from "@/components/ui/card";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { BrainCircuit, Play, AlertTriangle } from "lucide-react";
import { Button } from "../ui/button";

export function ScenarioInfo() {
  const { scenario, runPipeline, pipelineStatus } = useDevopsSim();

  if (!scenario) return null;

  const handleRunPipeline = () => {
    runPipeline();
  };

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center gap-3">
            <BrainCircuit className="h-6 w-6 text-primary"/>
            <CardTitle>AI-Generated Case Scenario</CardTitle>
        </div>
        <CardDescription>This is a dynamic, one-time simulation generated by AI.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div>
            <h3 className="font-semibold">{scenario.scenarioTitle}</h3>
            <p className="text-sm text-muted-foreground">{scenario.scenarioDescription}</p>
        </div>
        {scenario.isIncident && (
            <Alert variant="warning">
              <AlertTriangle className="h-4 w-4" />
              <AlertTitle>Incident Scenario</AlertTitle>
              <AlertDescription>
                This scenario simulates a problem. The pipeline is expected to fail.
              </AlertDescription>
            </Alert>
        )}
      </CardContent>
      <CardFooter>
        <Button onClick={handleRunPipeline} disabled={pipelineStatus !== 'idle'} className="w-full">
            <Play className="mr-2 h-4 w-4" />
            {pipelineStatus === 'idle' ? 'Run Pipeline' : 'Pipeline Running...'}
        </Button>
      </CardFooter>
    </Card>
  );
}
